### PR TITLE
Fetch and display data from the API

### LINKED ISSUE #64: Replace placeholders with actual data from the API
Now that the API starts to have the required endpoints, the front end needs to fetch the data from them and display it.

### PR DESCRIPTION
**Pull request by AlbertoPdRF**
Fixes #64.

### CODE REVIEW

**Comment by AlbertoPdRF** [comment]
Please see [the deploy preview](https://5f103069460a370008aa79fe--fellowship-companion.netlify.app/)! The client is unable to fetch from the API, it's getting the same CORS error @LakshyaKhatri @SaurabhAgarwala

**Comment by LakshyaKhatri** [comment]
This looks so dope :heart_eyes:

**Review by LakshyaKhatri — APPROVED** [review]

**Comment by AlbertoPdRF** [comment]
> Please see [the deploy preview](https://5f103069460a370008aa79fe--fellowship-companion.netlify.app/)! The client is unable to fetch from the API, it's getting the same CORS error @LakshyaKhatri @SaurabhAgarwala

See #71.

**Comment by SaurabhAgarwala** [comment]
The UI looks really good. Merging this PR as the CORS has been solved now

**Review by SaurabhAgarwala — APPROVED** [review]

**Comment by AlbertoPdRF** [comment]
Let's wait merging it until #73 is merged and deployed, so that we are sure everything is working before proceeding!

**Comment by AlbertoPdRF** [comment]
Ok, after #73 I can get everything to work locally, but we have a different error in production: `Mixed Content: The page at 'https://deploy-preview-69--fellowship-companion.netlify.app/' was loaded over HTTPS, but requested an insecure resource 'http://34.69.147.19:8000/api/v1/overview'. This request has been blocked; the content must be served over HTTPS.`. We need to serve our API through HTTPS. Can you also take care of this @SaurabhAgarwala?

However, as the code from this PR seems to work perfectly, I'll merge the PR!

**Comment by SaurabhAgarwala** [comment]
Ok, I am not sure of how to add a security certificate in the cloud instance. But I ll have a look over it.

**Pull request merged**
