### PR TITLE
Update landing screen image in README

### LINKED ISSUE #121: Update Landing Screen Image in Readme

### PR DESCRIPTION
**Pull request by SaurabhAgarwala**
Fixes #121

### CODE REVIEW

**Review by AlbertoPdRF — APPROVED** [review]
This looks good to me, unless we want to keep the macOS window layout.

**Review by LakshyaKhatri — CHANGES_REQUESTED** [review]
use this to beautify image: https://www.screely.com/

**Comment by SaurabhAgarwala** [comment]
> This looks good to me, unless we want to keep the macOS window layout.

I am not having macOS, so I can't add that :/

**Comment by SaurabhAgarwala** [comment]
> use this to beautify image: https://www.screely.com/

Thanks for the suggestion. I have updated it with this one

**Review by AlbertoPdRF — APPROVED** [review]
Looks perfect!

**Review by LakshyaKhatri — APPROVED** [review]

**Pull request merged**
