### PR TITLE
Add DB with data

### PR DESCRIPTION
**Pull request by SaurabhAgarwala**
This PR updates the DB with data

### CODE REVIEW

**Comment by LakshyaKhatri** [comment]
we can't do that, db will be changing every single second :confused:

**Comment by SaurabhAgarwala** [comment]
Wait I didn't get you

**Review by LakshyaKhatri — APPROVED** [review]

**Comment by LakshyaKhatri** [comment]
wait don't merge it. let me complete a pr first

**Comment by SaurabhAgarwala** [comment]
Merging it now. Approved by @LakshyaKhatri on discord

**Pull request merged**
