### PR TITLE
Create homepage

### LINKED ISSUE #25: Create the homepage
As discussed, the homepage should have:

> 1. Overview
> 2. Lines of code
> 3. Timeline
> 4. Users
> 5. Repositories
> 6. Footer

We didn't discuss it, but we should also have a navigation bar! The navigation bar and the footer would be present on the whole app.

### PR DESCRIPTION
**Pull request by AlbertoPdRF**
This is the proposed homepage:

Homepage

I thought that mimicking the Fellowship's logo would be a good idea, what do you guys think?

For now I haven't added a navigation bar nor a footer, as this PR is quite big already and I'd rather do that on a separate one.

Fixes #25.

### CODE REVIEW

**Comment by LakshyaKhatri** [comment]
looks good, just change the "supports" text to "has contributed".

**Comment by AlbertoPdRF** [comment]
As I already used "contribute" above, I didn't want to repeat it. Any other suggestion?

**Comment by LakshyaKhatri** [comment]
"contributing to"? :laughing:

**Comment by LakshyaKhatri** [comment]
Also, I would encourage to keep the design simpler and not to complicate things much. :smile:

**Comment by AlbertoPdRF** [comment]
What do you think it's not simple?

**Comment by LakshyaKhatri** [comment]
No doubt it looks good. I was just wishing to go with classic website design so that we can do rapid development :smile_cat:

**Comment by AlbertoPdRF** [comment]
And what makes this so different from classic website design? It's just some CSS, it won't make the development any faster nor slower. Also, the design of other pages can (and probably will) be different anyway.

**Comment by LakshyaKhatri** [comment]
oops my bad, I guess! I thought it would have been a nightmare for you to create this design and to align things :rofl:. If it was easy then we can do more things like this. I loved this thing. (I'm really sorry if my words made you feel like I am judging your skills, I didn't mean that)

**Comment by AlbertoPdRF** [comment]
Don't worry, I didn't think that! I just wasn't able to fully-grasp what you were trying to say, written communication is not always easy 🙂

I'm glad you like it! I'll see if it makes sense to replicate stuff like this on other pages when the time comes 😄

**Comment by LakshyaKhatri** [comment]
Should I merge the changes?

**Comment by AlbertoPdRF** [comment]
Let's wait a bit for @SaurabhAgarwala's opinion

**Comment by LakshyaKhatri** [comment]
Sure

**Comment by AlbertoPdRF** [comment]
I'm merging this now!

**Pull request merged**
