### PR TITLE
Add team Model

### LINKED ISSUE #42: Add Teams model
Add a team model for handling teams on github

### PR DESCRIPTION
**Pull request by LakshyaKhatri**
Fixes #42

### CODE REVIEW

**Review by AlbertoPdRF — COMMENTED** [review]
Given that we use `Fellow` instead of `User`, should we use `Pod` instead of `Team`?

**Comment by LakshyaKhatri** [comment]
we will be changing `Fellow` to `GithubUser` since we have to add mentors and staff people too in it.

**Comment by LakshyaKhatri** [comment]
Merging this, since other work depends on it.

**Comment by AlbertoPdRF** [comment]
> we will be changing `Fellow` to `GithubUser` since we have to add mentors and staff people too in it.

Ahh, gotcha!

**Pull request merged**
